/**
 * Arrival at altitude (Design Notes 10 §3 and §5).
 *
 * Two authored tables, both keyed by the tier being *entered*:
 *
 *   - what the Interlude hands the player (§3)
 *   - what the rivals waiting there have already built (§5)
 *
 * The second one is the load-bearing rule. DN10 §5 is explicit that a rival's
 * arriving warband is never generated by copying or scaling the player's
 * board: mirror-scaling makes building pointless, because out-building the
 * lobby just raises the lobby. Fixing the reference point instead is what lets
 * a strong campaign actually feel strong. Nothing here may read the player.
 *
 * These are the harness's numbers to tune (§6), not the designer's to fix:
 * `npm run sim -- --campaign` reports the delta between where real arriving
 * boards sit and where the budget says they should.
 */

/** DN10 §3: one extra talent point per Interlude, on top of the level-up six. */
export const INTERLUDE_TALENT_POINTS = 1

export interface ArrivalBudget {
  tier: number
  /**
   * Gold a rival has already spent building its board when you arrive. Handed
   * to the ordinary rival Muster policy in slices rather than spent by a
   * special-case builder, so an arriving rival is a board the game could
   * actually have produced — and stays subject to every tier rule.
   */
  spend: number
  /** the camp tier it arrives holding, so its offers are altitude-appropriate */
  campTier: number
  /** talent points already walked, by the same archetype policy rivals use */
  talents: number
  /**
   * The player's opening gold on arriving here (§3: base income plus one War
   * Chest-sized grant). Gold never banks across a boundary — hoarding at an
   * easy tier to buy out a hard one would flatten the climb.
   */
  stipend: number
}

/**
 * Tier 1 is listed for completeness and is never used: a campaign starts there
 * and nobody ever *arrives*. Its zeroes are what make "a campaign that never
 * marches is unchanged" true by construction rather than by a special case.
 */
export const ARRIVAL_BUDGETS: ArrivalBudget[] = [
  { tier: 1, spend: 0, campTier: 1, talents: 0, stipend: 0 },
  { tier: 2, spend: 26, campTier: 2, talents: 2, stipend: 12 },
  { tier: 3, spend: 40, campTier: 3, talents: 3, stipend: 14 },
  { tier: 4, spend: 54, campTier: 3, talents: 4, stipend: 16 },
  { tier: 5, spend: 68, campTier: 4, talents: 4, stipend: 18 },
  { tier: 6, spend: 82, campTier: 4, talents: 5, stipend: 20 },
  { tier: 7, spend: 96, campTier: 5, talents: 5, stipend: 22 },
  { tier: 8, spend: 110, campTier: 5, talents: 6, stipend: 24 },
  { tier: 9, spend: 124, campTier: 5, talents: 6, stipend: 26 },
  { tier: 10, spend: 138, campTier: 5, talents: 6, stipend: 28 },
]

export const arrivalFor = (tier: number): ArrivalBudget =>
  ARRIVAL_BUDGETS.find((b) => b.tier === tier) ?? ARRIVAL_BUDGETS[ARRIVAL_BUDGETS.length - 1]

/** The player's opening gold on arriving at this tier (§3). */
export const stipendFor = (tier: number): number => arrivalFor(tier).stipend
