// GENERATED by Bannerfell_Art/tools/make_drop.py — do not hand-edit.

export const UNIT_ART: Record<string, string> = {
  vg_militia: '/art/units/vg_militia.webp',
  vg_crossbow: '/art/units/vg_crossbow.webp',
  vg_mule: '/art/units/vg_mule.webp',
  vg_footman: '/art/units/vg_footman.webp',
  vg_arbalest: '/art/units/vg_arbalest.webp',
  vg_shieldmaiden: '/art/units/vg_shieldmaiden.webp',
  vg_cleric: '/art/units/vg_cleric.webp',
  vg_champion: '/art/units/vg_champion.webp',
  vg_cannon: '/art/units/vg_cannon.webp',
  vg_colossus: '/art/units/vg_colossus.webp',
  vd_sapling: '/art/units/vd_sapling.webp',
  vd_dryad: '/art/units/vd_dryad.webp',
  vd_grovetender: '/art/units/vd_grovetender.webp',
  vd_thornbark: '/art/units/vd_thornbark.webp',
  vd_moonshade: '/art/units/vd_moonshade.webp',
  vd_glade: '/art/units/vd_glade.webp',
  vd_stag: '/art/units/vd_stag.webp',
  vd_elderbark: '/art/units/vd_elderbark.webp',
  vd_warden: '/art/units/vd_warden.webp',
  vd_ancient: '/art/units/vd_ancient.webp',
  st_raider: '/art/units/st_raider.webp',
  st_slinger: '/art/units/st_slinger.webp',
  st_drummer: '/art/units/st_drummer.webp',
  st_reaver: '/art/units/st_reaver.webp',
  st_harpooner: '/art/units/st_harpooner.webp',
  st_wolfrider: '/art/units/st_wolfrider.webp',
  st_shaman: '/art/units/st_shaman.webp',
  st_warlord: '/art/units/st_warlord.webp',
  st_roc: '/art/units/st_roc.webp',
  st_leviathan: '/art/units/st_leviathan.webp',
  mc_roadwarden: '/art/units/mc_roadwarden.webp',
  mc_factor: '/art/units/mc_factor.webp',
  mc_hedgeknight: '/art/units/mc_hedgeknight.webp',
  mc_bowman: '/art/units/mc_bowman.webp',
  mc_assassin: '/art/units/mc_assassin.webp',
  mc_pikewall: '/art/units/mc_pikewall.webp',
  mc_engineer: '/art/units/mc_engineer.webp',
  mc_wyrm: '/art/units/mc_wyrm.webp',
}

export const HERO_ART: Record<string, string> = {
  h_berrik: '/art/heroes/h_berrik.webp',
  h_yseult: '/art/heroes/h_yseult.webp',
  h_sylvaen: '/art/heroes/h_sylvaen.webp',
  h_maravel: '/art/heroes/h_maravel.webp',
  h_grommash: '/art/heroes/h_grommash.webp',
  h_zhala: '/art/heroes/h_zhala.webp',
}

export const HERO_ART_2X: Record<string, string> = {
  h_berrik: '/art/heroes/h_berrik@2x.webp',
  h_yseult: '/art/heroes/h_yseult@2x.webp',
  h_sylvaen: '/art/heroes/h_sylvaen@2x.webp',
  h_maravel: '/art/heroes/h_maravel@2x.webp',
  h_grommash: '/art/heroes/h_grommash@2x.webp',
  h_zhala: '/art/heroes/h_zhala@2x.webp',
}

/** Waist-up crop, face high in frame — never centre these. */
export const ART_OBJECT_POSITION = '50% 8%'
