// Originally GENERATED by Bannerfell_Art/tools/make_drop.py. The DN11 entries
// below were added by hand — that toolchain does not live in this repo, so the
// manifest and the generator have drifted apart and this file is now the source
// of truth. Reconciling the generator is art-side work; until then, add new
// plates here directly rather than trusting a regeneration to keep them.
// `tests/art.test.ts` is what actually holds the manifest and public/art
// together, in both directions.

export const UNIT_ART: Record<string, string> = {
  vg_militia: '/art/units/vg_militia.webp',
  vg_crossbow: '/art/units/vg_crossbow.webp',
  vg_mule: '/art/units/vg_mule.webp',
  vg_footman: '/art/units/vg_footman.webp',
  vg_arbalest: '/art/units/vg_arbalest.webp',
  vg_ballistier: '/art/units/vg_ballistier.webp',
  vg_shieldmaiden: '/art/units/vg_shieldmaiden.webp',
  vg_cleric: '/art/units/vg_cleric.webp',
  vg_champion: '/art/units/vg_champion.webp',
  vg_cannon: '/art/units/vg_cannon.webp',
  vg_colossus: '/art/units/vg_colossus.webp',
  vd_sapling: '/art/units/vd_sapling.webp',
  vd_dryad: '/art/units/vd_dryad.webp',
  vd_grovetender: '/art/units/vd_grovetender.webp',
  vd_thornbark: '/art/units/vd_thornbark.webp',
  vd_moonshade: '/art/units/vd_moonshade.webp',
  vd_matriarch: '/art/units/vd_matriarch.webp',
  vd_glade: '/art/units/vd_glade.webp',
  vd_stag: '/art/units/vd_stag.webp',
  vd_elderbark: '/art/units/vd_elderbark.webp',
  vd_warden: '/art/units/vd_warden.webp',
  vd_ancient: '/art/units/vd_ancient.webp',
  st_raider: '/art/units/st_raider.webp',
  st_slinger: '/art/units/st_slinger.webp',
  st_drummer: '/art/units/st_drummer.webp',
  st_reaver: '/art/units/st_reaver.webp',
  st_harpooner: '/art/units/st_harpooner.webp',
  st_stormspear: '/art/units/st_stormspear.webp',
  st_wolfrider: '/art/units/st_wolfrider.webp',
  st_shaman: '/art/units/st_shaman.webp',
  st_warlord: '/art/units/st_warlord.webp',
  st_roc: '/art/units/st_roc.webp',
  st_leviathan: '/art/units/st_leviathan.webp',
  mc_roadwarden: '/art/units/mc_roadwarden.webp',
  mc_factor: '/art/units/mc_factor.webp',
  mc_hedgeknight: '/art/units/mc_hedgeknight.webp',
  mc_bowman: '/art/units/mc_bowman.webp',
  mc_assassin: '/art/units/mc_assassin.webp',
  mc_pikewall: '/art/units/mc_pikewall.webp',
  mc_engineer: '/art/units/mc_engineer.webp',
  mc_wyrm: '/art/units/mc_wyrm.webp',

  // ── DN11 ────────────────────────────────────────────────────────────────
  // the Forgeline and the Bannerguard (§2.2, §2.3)
  vg_apprentice: '/art/units/vg_apprentice.webp',
  vg_runesmith: '/art/units/vg_runesmith.webp',
  vg_runelord: '/art/units/vg_runelord.webp',
  vg_warsmith: '/art/units/vg_warsmith.webp',
  vg_anvilborn: '/art/units/vg_anvilborn.webp',
  vg_bannerguard: '/art/units/vg_bannerguard.webp',
  // the Seedline and the Nightblade
  vd_whisperseed: '/art/units/vd_whisperseed.webp',
  vd_oakfather: '/art/units/vd_oakfather.webp',
  vd_oakheart: '/art/units/vd_oakheart.webp',
  vd_blackthorn: '/art/units/vd_blackthorn.webp',
  vd_reaper: '/art/units/vd_reaper.webp',
  vd_nightblade: '/art/units/vd_nightblade.webp',
  // the Whelpline and the Windspeaker
  st_whelp: '/art/units/st_whelp.webp',
  st_drake: '/art/units/st_drake.webp',
  st_wyvern: '/art/units/st_wyvern.webp',
  st_deepmaw: '/art/units/st_deepmaw.webp',
  st_alpha: '/art/units/st_alpha.webp',
  st_windspeaker: '/art/units/st_windspeaker.webp',

  // ── DN12 ────────────────────────────────────────────────────────────────
  // the roots the Shieldmaiden and Colossus lines never had (§3.4, §3.5)
  vg_shieldgirl: '/art/units/vg_shieldgirl.webp',
  vg_cairn: '/art/units/vg_cairn.webp',
  vg_bulwark: '/art/units/vg_bulwark.webp',
}

export const HERO_ART: Record<string, string> = {
  h_berrik: '/art/heroes/h_berrik.webp',
  h_yseult: '/art/heroes/h_yseult.webp',
  h_sylvaen: '/art/heroes/h_sylvaen.webp',
  h_maravel: '/art/heroes/h_maravel.webp',
  h_grommash: '/art/heroes/h_grommash.webp',
  h_zhala: '/art/heroes/h_zhala.webp',
}

export const HERO_ART_2X: Record<string, string> = {
  h_berrik: '/art/heroes/h_berrik@2x.webp',
  h_yseult: '/art/heroes/h_yseult@2x.webp',
  h_sylvaen: '/art/heroes/h_sylvaen@2x.webp',
  h_maravel: '/art/heroes/h_maravel@2x.webp',
  h_grommash: '/art/heroes/h_grommash@2x.webp',
  h_zhala: '/art/heroes/h_zhala@2x.webp',
}

/** Waist-up crop, face high in frame — never centre these. */
export const ART_OBJECT_POSITION = '50% 8%'
